name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++ ../  # Use g++ for Ubuntu
          cmake --build .
      
      - name: Rename file based on OS
        run: |
          mv ./build/blackjack ./build/blackjack_ubuntu

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++ ../  # Use clang++ for macOS
          cmake --build .
      
      - name: Rename file based on OS
        run: |
          mv ./build/blackjack ./build/blackjack_ubuntu

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [cl]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=cl ../  # Use cl for Windows
          cmake --build .
      
      - name: Rename file based on OS
        run: |
          mv ./build/blackjack.exe ./build/blackjack_ubuntu.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}