name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++ ../
          cmake --build .
      
      - name: Rename file based on OS
        run: |
          mv ./build/blackjack ./build/blackjack_ubuntu

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++ ../
          cmake --build .
      
      - name: Rename file based on OS
        run: |
          mv ./build/blackjack ./build/blackjack_macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          choco install llvm
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++ ../
          cmake --build .
      
      - name: Rename file based on OS
        run: |
          mv ./build/blackjack.exe ./build/blackjack_windows.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}