name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ../
          cmake --build .

      - name: Determine executable extension
        id: get_extension
        run: |
          case ${{ matrix.os }} in
            ubuntu-latest|macos-latest)
              echo "::set-output name=extension::"
              ;;
            windows-latest)
              echo "::set-output name=extension::.exe"
              ;;
          esac

      - name: Rename file based on OS
        run: |
          case ${{ matrix.os }} in
            ubuntu-latest)
              mv ./build/blackjack${{ steps.get_extension.outputs.extension }} ./build/blackjack_ubuntu${{ steps.get_extension.outputs.extension }}
              ;;
            macos-latest)
              mv ./build/blackjack${{ steps.get_extension.outputs.extension }} ./build/blackjack_macos${{ steps.get_extension.outputs.extension }}
              ;;
            windows-latest)
              mv ./build/blackjack${{ steps.get_extension.outputs.extension }} ./build/blackjack_windows${{ steps.get_extension.outputs.extension }}
              ;;
          esac

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/blackjack*
          tag_name: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}
